# Generated by Django 4.2.7 on 2023-11-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
