# Generated by Django 4.2.7 on 2023-11-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_card_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='product',
        ),
        migrations.RemoveField(
            model_name='card',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cart',
            field=models.ManyToManyField(to='ecom.cartitem'),
        ),
    ]
