# Generated by Django 4.2.7 on 2023-11-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_remove_card_product_remove_card_quantity_cartitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='carts',
        ),
    ]
