# Generated by Django 4.2.7 on 2023-11-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_alter_cart_options_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='carts',
            field=models.ManyToManyField(blank=True, null=True, to='ecom.cartitem'),
        ),
    ]
