# Generated by Django 4.2.7 on 2023-11-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_alter_cart_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
